networks:
  sns-net:
    ipam:
      config:
        - subnet: 172.31.0.0/16

volumes:
  socket:
    driver: local
  log:
    driver: local
  docroot:
    driver: local

services:
  reverse_proxy:
    image: nginx:latest
    container_name: reverse_proxy
    networks:
      - sns-net
    ports:
      - "8080:80"
    volumes:
      - ./docroot:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
